name: Validate Consilium Docs

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run docs validator
        run: |
          python scripts/validate_docs.py
